#!/usr/bin/env python

import json
from copy import deepcopy
from sys import argv, exit

if len(argv) < 3:
    print "Usage: %s old_config.conf new_config.conf" % argv[0]
    exit(1)

old_config = json.load(open(argv[1]))


if (isinstance(old_config["groups"], list)):
    print "Your configfile is already supported"
    exit(2)

new_config = deepcopy(old_config)
new_config["groups"] = []

for key in old_config["groups"].keys():
    item = {}
    item["name"] = deepcopy(key)
    for nkey in old_config["groups"][key]:
        item[nkey] = deepcopy(old_config["groups"][key][nkey])

    # parse channel names
    for ndx, value in enumerate(item["channels"]):
        item["channels"][ndx] = value.replace("/devices/", "", 1).replace("controls/", "", 1)

    new_config["groups"].append(item)

json.dump(new_config, open(argv[2], "w"), indent=4)

print "New configfile is ready"

exit(0)
