#!/bin/bash
. /etc/wb_env.sh

CONFFILE=/etc/wb-homa-adc.conf

case "$WB_VERSION" in
    "41" )
        BOARD_CONF="/usr/share/wb-homa-adc/wb-homa-adc.conf"
    ;;

    "32" )
        BOARD_CONF="/usr/share/wb-homa-adc/wb-homa-adc.conf.wbsh3"
    ;;

    "KMON1" )
        BOARD_CONF="/usr/share/wb-homa-adc/wb-homa-adc.conf.wb2.8"
    ;;

    * )
        BOARD_CONF="/usr/share/wb-homa-adc/wb-homa-adc.conf"
    ;;
esac


ucf --debconf-ok $BOARD_CONF $CONFFILE


#DEBHELPER#

